# Profile Configuration
name = "Mike Fiedler"
title = "Code Gardener"
description = "Building better software, one commit at a time. Open source contributor and Python enthusiast."
avatar = "https://miketheman.dev/avatar.png"
site_url = "https://miketheman.dev"

# Note: The order of the sections determines the output order.

[[links]]
url = "https://github.com/miketheman"
label = "GitHub"
icon = "fa-brands fa-github"

[[links]]
url = "https://bsky.app/profile/miketheman.com"
label = "Bluesky"
icon = "fa-brands fa-bluesky"

[[links]]
url = "https://hachyderm.io/@miketheman"
icon = "fa-brands fa-mastodon"
label = "Mastodon"

[[links]]
url = "https://www.linkedin.com/in/miketheman/"
label = "LinkedIn"
icon = "fa-brands fa-linkedin"

[[links]]
url = "https://www.miketheman.net/"
label = "Personal Blog"
icon = "fa-solid fa-blog"

[[links]]
url = "https://blog.pypi.org/"
label = "PyPI Blog"
icon = "fa-brands fa-python"

[[extras]]
label = "DevOpsDays Tel Aviv 2025 - Moving Mountains - companion"
url = "https://gist.github.com/miketheman/eb4e7214afd7372d5080d557f70a81bd"
icon = "fa-solid fa-person-chalkboard"
date = "2025-12-11"
