# Profile Configuration
name = "Mike Fiedler"
title = "Code Gardener"
description = "Building better software, one commit at a time. Open source contributor and Python enthusiast."
avatar = "https://miketheman.dev/avatar.png"
site_url = "https://miketheman.dev"

# Note: The order of the sections determines the output order.

[[links]]
url = "https://github.com/miketheman"
label = "GitHub"
icon = "fa-brands fa-github"

[[links]]
url = "https://bsky.app/profile/miketheman.com"
label = "Bluesky"
icon = "fa-brands fa-bluesky"

[[links]]
url = "https://hachyderm.io/@miketheman"
icon = "fa-brands fa-mastodon"
label = "Mastodon"

[[links]]
url = "https://www.linkedin.com/in/miketheman/"
label = "LinkedIn"
icon = "fa-brands fa-linkedin"

[[links]]
url = "https://www.miketheman.net/"
label = "Personal Blog"
icon = "fa-solid fa-blog"

[[links]]
url = "https://blog.pypi.org/"
label = "PyPI Blog"
icon = "fa-brands fa-python"

# Extras Section - Additional presentations, talks, resources
[[extras]]
label = "PyCon US 2024 - Security in Python Packaging"
url = "https://www.youtube.com/watch?v=example"
icon = "fa-solid fa-presentation"
date = "May 15, 2024"

[[extras]]
label = "Talk Slides & Resources"
url = "https://github.com/miketheman/talks"
icon = "fa-solid fa-file-pdf"
